# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    filters:
      branches:
        only:
        - dependabot/*

    docker:
    # specify the version you desire here
    - image: circleci/node:dubnium
      environment:
        PG_CONNECTION_STRING: postgres://postgres:postgres@localhost:5432/circle_test
    - image: circleci/postgres:9.6-alpine-postgis
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: circle_test

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
    - checkout

    - run: npm install

    # run tests!
    - run: npm test


